var national_days = {
  "1-2":"National Cream Puff Day",
  "1-4":"National Spaghetti Day",
  "1-5":"National Whipped Cream Day",
  "1-6":"National Cuddle Up Day",
  "1-11":"National Milk Day",
  "1-13":"National Sticker Day",
  "1-15":"National Strawberry Ice Cream Day",
  "1-19":"National Popcorn Day",
  "1-20":"National Cheese Lover’s Day",
  "1-21":"National Hugging Day",
  "1-24":"National Peanut Butter Day",
  "1-27":"National Chocolate Cake Day",
  "1-28":"National Blueberry Pancake Day",
  "1-30":"National Croissant Day",
  "1-31":"National Hot Chocolate Day",
  "2-2":"National Tater Tot Day",
  "2-5":"National Shower with a Friend Day",
  "2-9":"National Pizza Day",
  "2-11":"National Make a Friend Day",
  "2-17":"National Random Acts of Kindness Day",
  "2-18":"National Drink Wine Day",
  "2-20":"National Love Your Pet Day",
  "2-21":"National Sticky Bun Day",
  "2-22":"National Margarita Day",
  "2-23":"National Banana Bread Day",
  "2-27":"National Strawberry Day",
  "3-6":"National Frozen Food Day",
  "3-12":"National Plant a Flower Day",
  "3-14":"National Pi Day",
  "3-20":"National Ravioli Day",
  "3-21":"National French Bread Day",
  "3-22":"National Bavarian Crepes Day",
  "3-23":"National Puppy Day",
  "3-23":"National Chip and Dip Day",
  "3-30":"National Take a Walk in the Park Day",
  "3-31":"National Tater Day",
  "4-2":"National Peanut Butter and Jelly Day",
  "4-3":"National Chocolate Mousse Day",
  "4-4":"National Burrito Day – First Thursday in April",
  "4-5":"National Deep Dish Pizza Day",
  "4-7":"National Beer Day",
  "4-7":"National Coffee Cake Day",
  "4-10":"Ben & Jerry's Free Cone Day",
  "4-12":"National Grilled Cheese Sandwich Day",
  "4-22":"National Jelly Bean Day",
  "4-26":"National Pretzel Day",
  "4-28":"National Blueberry Pie Day",
  "4-30":"National Bubble Tea Day",
  "5-2":"National Truffle Day",
  "5-4":"National Star Wars Day",
  "5-5":"National Astronaut Day",
  "5-8":"National Coconut Cream Pie Day",
  "5-10":"National Clean Up Your Room Day",
  "5-12":"National Limerick Day",
  "5-15":"National Chocolate Chip Day",
  "5-17":"National Pizza Party Day – Third Friday in May",
  "5-21":"National Strawberries and Cream Day",
  "5-25":"National Wine Day",
  "5-26":"National Blueberry Cheesecake Day",
  "5-28":"National Hamburger Day",
  "5-31":"National Smile Day",
  "6-1":"National Say Something Nice Day",
  "6-3":"National Egg Day",
  "6-4":"National Cheese Day",
  "6-5":"National Veggie Burger Day",
  "6-7":"National Chocolate Ice Cream Day",
  "6-7":"National Doughnut Day – First Friday in June",
  "6-14":"International Bath Day",
  "6-14":"National Strawberry Shortcake Day",
  "6-19":"National Martini Day",
  "6-20":"National Vanilla Milkshake Day",
  "6-22":"National Chocolate Eclair Day",
  "6-22":"National Onion Rings Day",
  "6-23":"National Hydration Day",
  "6-26":"National Chocolate Pudding Day",
  "6-27":"National Ice Cream Cake Day",
  "6-30":"National Meteor Watch Day",
  "7-6":"National Fried Chicken Day",
  "7-10":"National Pina Colada Day",
  "7-11":"National Blueberry Muffin Day",
  "7-12":"National Different Colored Eyes Day",
  "7-12":"National Pecan Pie Day",
  "7-13":"National French Fry Day",
  "7-14":"National Nude Day",
  "7-14":"National Mac & Cheese Day",
  "7-17":"World Emoji Day",
  "7-21":"National Ice Cream Day – Third Sunday in July",
  "7-23":"National Hot Dog Day",
  "7-23":"National Vanilla Ice Cream Day",
  "7-24":"National Drive-Thru Day",
  "7-25":"National Hot Fudge Sundae Day",
  "7-26":"National Bagelfest Day",
  "7-30":"National Cheesecake Day",
  "7-31":"National Avocado Day",
  "8-2":"National Ice Cream Sandwich Day",
  "8-3":"International Beer Day",
  "8-4":"National Chocolate Chip Cookie Day",
  "8-6":"National Root Beer Float Day",
  "8-10":"National S’mores Day",
  "8-15":"National Lemon Meringue Pie Day",
  "8-24":"National Waffle Day",
  "8-25":"National Banana Split Day",
  "8-26":"National Dog Day",
  "9-5":"National Cheese Pizza Day",
  "9-6":"National Read A Book Day",
  "9-11":"National Make Your Bed Day",
  "9-12":"National Video Games Day",
  "9-12":"National Chocolate Milkshake Day",
  "9-13":"National Programmers Day – 256th Day of the Year",
  "9-15":"National Double Cheeseburger Day",
  "9-18":"National Cheeseburger Day",
  "9-20":"National Fried Rice Day",
  "9-20":"National Pepperoni Pizza Day",
  "9-22":"Elephant Appreciation Day",
  "9-25":"National Comic Book Day",
  "9-25":"National Lobster Day",
  "9-26":"National Pancake Day",
  "9-27":"National Chocolate Milk Day",
  "9-28":"National Drink Beer Day",
  "9-29":"National Coffee Day",
  "10-3":"National Boyfriend Day",
  "10-4":"National Taco Day",
  "10-7":"National LED Light Day",
  "10-9":"National Leif Erikson Day",
  "10-11":"National Sausage Pizza Day",
  "10-12":"National Vermont Day",
  "10-13":"National No Bra Day",
  "10-16":"Global Cat Day",
  "10-18":"National Chocolate Cupcake Day",
  "10-22":"National Nut Day",
  "10-23":"National Boston Cream Pie Day",
  "10-26":"National Pumpkin Day",
  "10-28":"National Chocolate Day",
  "11-3":"National Sandwich Day",
  "11-5":"National Doughnut Day",
  "11-11":"National Sundae Day",
  "11-14":"National Pickle Day",
  "11-17":"National Take A Hike Day",
  "11-25":"National Parfait Day",
  "11-26":"National Cake Day",
  "11-28":"National French Toast Day",
  "12-1":"National Pie Day",
  "12-4":"National Cookie Day",
  "12-8":"National Brownie Day",
  "12-13":"National Cocoa Day",
  "12-17":"National Maple Syrup Day",
  "12-30":"Bacon Day"
};
